### ISSUE TITLE
Datepicker Initialize with Options dayLabels do not work.

### ISSUE THREAD

**Issue by scoppys** [appiphony/appiphony-lightning-js#43]
Hi i set this  init options

`
$(document).ready(function() {
    $('#date').datepicker({
        numYearsBefore: 50,
        numYearsAfter: 10,
        format: 'MM/DD/YYYY',
        initDate: moment(),
        dayLabels: [
            {
                full: 'Domenica',
                abbv: 'Dom'
            },
            {
                full: 'Luned&#236',
                abbv: 'Lun'
            },
            {
                full: 'Marted&#236',
                abbv: 'Mar'
            },
            {
                full: 'Mercoled&#236',
                abbv: 'Mer'
            },
            {
                full: 'Gioved&#236',
                abbv: 'Gio'
            },
            {
                full: 'Venerd&#236',
                abbv: 'Ven'
            },
            {
                full: 'Sabato',
                abbv: 'Sab'
            }
        ],
        monthLabels: [
            {
                full: 'Gennaio',
                abbv: 'Gen'
            },
            {
                full: 'Febbraio',
                abbv: 'Feb'
            },
            {
                full: 'Marzo',
                abbv: 'Mar'
            },
            {
                full: 'Aprile',
                abbv: 'Apr'
            },
            {
                full: 'Maggio',
                abbv: 'Mag'
            },
            {
                full: 'Giugno',
                abbv: 'Giu'
            },
            {
                full: 'Luglio',
                abbv: 'Lug'
            },
            {
                full: 'Agosto',
                abbv: 'Ago'
            },
            {
                full: 'Settembre',
                abbv: 'Set'
            },
            {
                full: 'Ottobre',
                abbv: 'Ott'
            },
            {
                full: 'Novembre',
                abbv: 'Nov'
            },
            {
                full: 'Dicembre',
                abbv: 'Dic'
            }
        ],
        onChange: function(datepicker) {
            console.log(datepicker);
        }
    });
});`

but Datepicker use default name for dayLabels

**Comment by kevinberonilla** [comment]
Thank you for logging this! We will be looking into this as we refactor the plugins to support SLDS 2.x and we'll get back to you as soon as possible.

**Comment by scoppys** [comment]
there is a  date for the new release  with bug fixed?

**Comment by kevinberonilla** [comment]
We currently do not have a target date set for the new release. We do hope to get through as many issues as possible in the coming days. The `development` branch is actively being worked on for the transition to SLDS 2.x markup support, and we will let you know when your fix is available in that branch.

**Comment by kevinberonilla** [comment]
Hello @scoppys, can you please test this file? https://github.com/appiphony/appiphony-lightning-js/blob/development/dist/jquery/jquery.aljs-datepicker.min.js

That is the datepicker plugin from our `development` branch. I would advise using this single plugin instead of the aljs-all file since there are several other plugins in the aljs-all file that are currently being reworked.

**Comment by scoppys** [comment]
Hi  @kevinberonilla ,  the bug is still present 

`jquery.aljs-init.min.js 
and 
https://github.com/appiphony/appiphony-lightning-js/blob/development/dist/jquery/jquery.aljs-datepicker.min.js

with this 

$('#date').datepicker({
        numYearsBefore: 50,
        numYearsAfter: 10,
        format: 'MM/DD/YYYY',
        initDate: moment(),
        dayLabels: [
            {
                full: 'Sunday',
                abbv: 'S'
            },
            {
                full: 'Monday',
                abbv: 'M'
            },
            {
                full: 'Tuesday',
                abbv: 'T'
            },
            {
                full: 'Wednesday',
                abbv: 'W'
            },
            {
                full: 'Thursday',
                abbv: 'T'
            },
            {
                full: 'Friday',
                abbv: 'F'
            },
            {
                full: 'Saturday',
                abbv: 'S'
            }
        ],
        monthLabels: [
            {
                full: 'January',
                abbv: ''
            },
            {
                full: 'February',
                abbv: ''
            },
            {
                full: 'March',
                abbv: ''
            },
            {
                full: 'April',
                abbv: ''
            },
            {
                full: 'May',
                abbv: ''
            },
            {
                full: 'June',
                abbv: ''
            },
            {
                full: 'July',
                abbv: ''
            },
            {
                full: 'August',
                abbv: ''
            },
            {
                full: 'September',
                abbv: ''
            },
            {
                full: 'October',
                abbv: ''
            },
            {
                full: 'November',
                abbv: ''
            },
            {
                full: 'December',
                abbv: ''
            }
        ],
        onChange: function(datepicker) {
            console.log(datepicker);
        }
    });
`

i have a "undefined" in  short day format :( 
![datepickertransaleteerror](https://cloud.githubusercontent.com/assets/20538989/17057495/98d8d444-501a-11e6-9209-9869aa949a19.jpg)

**Comment by kevinberonilla** [comment]
Ahh I forgot to mention: please change all 'abbv' properties to 'abbr' as
this is a change we made recently on the development branch to match the
generated markup (which uses the <abbr> element).

**Comment by scoppys** [comment]
it is work for days and mounths....
Just how to translate the "today" link (i like have "oggi")?
![calendario2](https://cloud.githubusercontent.com/assets/20538989/17057877/65b9fa86-501d-11e6-97dc-82405b30d596.jpg)

**Comment by scoppys** [comment]
it is work for days and mounths....
Just how to translate the "today" link (i like have "oggi")?
![Uploading calendario2.jpg…]()

**Comment by kevinberonilla** [comment]
This is actually a great enhancement to support multiple languages on the Today link. I'm reopening this issue at least until this enhancement is ready for you on the `development` branch.

**Comment by kevinberonilla** [comment]
@scoppys can you download the latest development version and try out the new functionality? https://github.com/appiphony/appiphony-lightning-js/blob/development/dist/jquery/jquery.aljs-datepicker.min.js

You will just need to pass in a property called `todayLabel` that accepts a string representing the Today link's text.

**Comment by scoppys** [comment]
it is OK
![calendario3](https://cloud.githubusercontent.com/assets/20538989/17061288/0ff48c68-502e-11e6-927c-9c84c172b440.jpg)
!
`j$('#date').datepicker({
        todayLabel: 'Oggi', 
		dayLabels: [.......`
