### ISSUE TITLE
Icons in slds not displaying due to unsafe attempt error

### ISSUE THREAD

**Issue by Lanceshi2** [appiphony/appiphony-lightning-js#57]
I am using Appyphony Lightning JS to create lookup relationship field for me. Everything else was working pretty well. But the slds icons are not displaying well. I am constantly getting the below error in chrome's developer tool:

> Unsafe attempt to load URL https://ap2.salesforce.com/assets/icons/standard-sprite/svg/symbols.svg#account from frame with URL https://v6.ap2.visual.force.com/apex/Auto_Subscription_Edit?retURL=%2Fa08%2Fo&save_new=1&sfdc.override=1. Domains, protocols and ports must match.

![image not displaying](https://cloud.githubusercontent.com/assets/9388090/20906173/875d94e6-bb92-11e6-8cd9-049d68e1e419.PNG)

I have added the initialization code as below:

        var assetsLocation = "{!URLFOR($Resource.Slds213, 'assets')}";
        $.aljsInit({
            assetsLocation: '',
            scoped: true
        });
Is there anything else I am missing here?

**Comment by kevinberonilla** [comment]
Hi @Lanceshi2,

This is most likely caused by the `assetsLocation` property not referencing your variable at the top. We actually just released a new version of our plugins as well as new documentation since this step for configuration used to be a bit vague.

Try this code instead:
```
    var assetsLocation = "{!URLFOR($Resource.Slds213, 'assets')}";
    $.aljsInit({
        assetsLocation: assetsLocation, // Note the change on this line
        scoped: true
    });
```

**Comment by Lanceshi2** [comment]
Hi @kevinberonilla , 

I have updated the code according to your suggestion. But I am still getting the same error. 

To clarify, I am using <use xlink:href="{!URLFOR($Resource.Slds213, 'assets/icons/custom-sprite/svg/symbols.svg#custom27')}"></use> to get the search icon which works fine for me. 

Also, the initialization code was used inside $(document).ready() function. Is there anything I ought to change here?

**Comment by Lanceshi2** [comment]
A bit more information here - I am developing a managed package with a namespace in this org. So there is a namespace - V6 here. It might be the cause of the issue.

**Comment by kevinberonilla** [comment]
That could very well be the case, but it's still strange that some icons are working and others not. Was the search icon working before?

Also, we had just released a new version (3.0.0) about an hour before you posted this issue. There was a bug that was fixed on the lookups plugin that involved some icons not properly reading the `assetsLocation` property on init. Can you please try the new version to see if that bugfix helps your case?

**Comment by Lanceshi2** [comment]
I have tried with the new version but still no luck. Actually none of the icons worked. The search icon was working because I am using the slds way to reference it - not the appiphony way. Is there a way to setup for the namespace?

**Comment by kevinberonilla** [comment]
Namespace-wise, `assetsLocation` would just need to reference the name of the resource with its namespace. This means in a development environment the variable will exclude namespaces and the packaging environment will include them to ensure the references are correct when installed in a production environment. It can be challenging to manage.

Can you please try one more thing? Try changing the the variable to the following:
```
var assetsLocation = "{!URLFOR($Resource.Slds213)}";
```

The `assetsLocation` is meant to specify the location of the assets directory (its parent), not the assets directory itself.

**Comment by Lanceshi2** [comment]
Cool. It is working very well now. Thank you, Kevin.
